version: '3.3'

services:
  webapp:
    environment:
      - DB_HOST=10.32.1.49
      - DB_USER=datlt
      - DB_PASS=a123456
    image: nodeapi:v3
    ports:
      - "3000:3000"
    networks:
      - bridge500
networks:
  bridge500:
    external: true 
